LibraryMngmnt.Web/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Web.Models.Branch;
using LibraryData;
using Microsoft.AspNetCore.Mvc;

namespace Library.Web.Controllers
{
    public class BranchController : Controller
    {
        private ILibraryBranch _branch;

        public BranchController (ILibraryBranch branch )
        {
            _branch=branch;
        }
        public IActionResult Index()
        {
            var branches = _branch.GetAll ( ).Select ( branch => new BranchDetailModel
            {
                Id=branch.Id,
                Name=branch.Name,
                IsOpen=_branch.IsBranchOpen ( branch.Id ),
                NumberOfAssets=_branch.GetAssets ( branch.Id ).Count ( ),
                NumberOfPatrons=_branch.GetPatrons ( branch.Id ).Count ( )
            } );

            var model = new BranchIndexModel ( )
            {
                Branches=branches
            };
            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var branch = _branch.Get ( id );
            var model = new BranchDetailModel
            {
                Id=branch.Id,
                Name=branch.Name,
                Address = branch.Address,
                Telephone = branch.Telephone,
                OpenDate = branch.OpenDate.ToString("yyyy-MM-dd"),
                NumberOfAssets= _branch.GetAssets(id).Count(),
                NumberOfPatrons=_branch.GetPatrons(id).Count(),
                TotalAssetValue=_branch.GetAssets(id).Sum(a => a.Cost),
                ImageUrl=branch.ImageUrl,
                HoursOpen=_branch.GetBranchHours(id)
            };

            return View ( model );

        }
    }
}

LibraryMngmnt.Web/Controllers/CatalogController.cs
using System.Linq;
using Library.Web.Models.Catalog;
using Library.Web.Models.CheckoutModels;
using LibraryData;
using Microsoft.AspNetCore.Mvc;

namespace Library.Web.Controllers
{
    public class CatalogController : Controller 
    {
        private readonly ILibraryAsset _assets;
        private readonly ICheckout _checkouts;

        public CatalogController ( ILibraryAsset assets, ICheckout checkouts )
        {
            _assets = assets;
            _checkouts = checkouts;
        }

        public IActionResult Index ( )
        {
            var assetModels = _assets.GetAll ( );

            var listingResult = assetModels
                .Select ( result => new AssetIndexListingModel
                {
                    Id=result.Id,
                    ImageUrl=result.ImageUrl,
                    AuthorOrDirector=_assets.GetAuthorOrDirector ( result.Id ),
                    DeweyCallNumber=_assets.GetDeweyIndex ( result.Id ),
                    Title=result.Title,
                    Type=_assets.GetType (result.Id)
                } );
            var model = new AssetIndexModel ( )
            {
                Assets=listingResult
            };
            return View (model);
        }

        public IActionResult Detail(int id )
        {
            var asset = _assets.GetById(id);

            var currentHolds = _checkouts.GetCurrentHolds(id)
                .Select( a => new AssetHoldModel
                {
                    HoldPlaced = _checkouts.GetCurrentHoldPlaced( a.Id ).ToString ( "d" ),
                    PatronName = _checkouts.GetCurrentHoldPatronName( a.Id )
                } );

            var model = new AssetDetailModel
            {
                AssetId = id,
                Title = asset.Title,
                Year = asset.Year,
                Cost = asset.Cost,
                Status = asset.Status.Name,
                ImageUrl = asset.ImageUrl,
                AuthorOrDirector = _assets.GetAuthorOrDirector ( id ),
                CurrentLocation = _assets.GetCurrentLocation ( id ).Name,
                DeweyCallNumber =_assets.GetDeweyIndex ( id ),
                ISBN = _assets.GetIsbn ( id ),
                CheckoutHistory = _checkouts.GetCheckoutHistory ( id ),
                LastestCheckout = _checkouts.GetLatestCheckout(id),
                PatronName = _checkouts.GetCurrentCheckedoutPatron(id),
                CurrentHolds = currentHolds                               
            };
            return View ( model );
        }

        public IActionResult Checkout(int id )
        {
            var asset = _assets.GetById ( id );
            var model = new CheckoutModel
            {
                AssetId=id,
                ImageUrl=asset.ImageUrl,
                Title=asset.Title,
                LibraryCardId="",
                IsCheckedOut=_checkouts.IsCheckedOut ( id )

            };

            return View ( model );
        }

        public IActionResult CheckIn(int id )
        {
            _checkouts.CheckInItem ( id );
            return RedirectToAction ( "Detail", new { id = id } );
        }

        public IActionResult Hold ( int id )
        {
            var asset = _assets.GetById ( id );
            var model = new CheckoutModel
            {
                AssetId=id,
                ImageUrl=asset.ImageUrl,
                Title=asset.Title,
                LibraryCardId="",
                IsCheckedOut=_checkouts.IsCheckedOut ( id ),
                HoldCount=_checkouts.GetCurrentHolds ( id ).Count ( )
            };

            return View ( model );
        }

        public IActionResult MarkLost(int assetId )
        {
            _checkouts.MarkLost ( assetId );
            return RedirectToAction("Detail", new { id = assetId});
        }

        public IActionResult MarkFound ( int assetId )
        {
            _checkouts.MarkFound ( assetId );
            return RedirectToAction ( "Detail", new { id = assetId } );
        }

        [HttpPost]
        public IActionResult PlaceCheckout(int assetId, int libraryCardId )
        {
            _checkouts.CheckOutItem ( assetId, libraryCardId );

            return RedirectToAction ( "Detail", new { id = assetId } );
        }

        [HttpPost]
        public IActionResult PlaceHold ( int assetId, int libraryCardId )
        {
                _checkouts.PlaceHold ( assetId, libraryCardId );

            return RedirectToAction ( "Detail", new { id = assetId } );
        }
    }
}

LibraryMngmnt.Web/Controllers/PatronController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Web.Models.Patron;
using LibraryData;
using LibraryData.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Library.Web.Controllers
{
    public class PatronController : Controller
    {
        private readonly IPatron _patron;

        public PatronController ( IPatron patron)
        {
            _patron = patron;
        }

        public IActionResult Index( )
        {
            var allPatrons = _patron.GetAll ( );
            var patronModels = allPatrons.Select ( p => new PatronDetailModel // essentially a mapping (think of .MAP )
            {
                Id = p.Id,
                FirstName = p.FirstName,
                LastName = p.LastName,
                LibraryCardId = p.LibraryCard.Id,
                OverdueFees = p.LibraryCard.Fees,
                HomeLibraryBranch = p.HomeLibraryBranch.Name

            } ).ToList();
            var model = new PatronIndexModel ( )
            {
                Patrons = patronModels
            };

            return View ( model );
        }

        public IActionResult Detail(int id)
        {
            var patron = _patron.Get ( id );

            var model = new PatronDetailModel
            {
                LastName=patron.LastName,
                FirstName=patron.FirstName,
                Address=patron.Address,
                HomeLibraryBranch=patron.HomeLibraryBranch.Name,
                MemberSince=patron.LibraryCard.Created,
                OverdueFees=patron.LibraryCard.Fees,
                LibraryCardId=patron.LibraryCard.Id,
                Telephone=patron.TelephoneNumber,
                AssetsCheckedOut=_patron.GetCheckouts ( id ).ToList ( )??new List<Checkout> ( ),
                CheckoutHistory=_patron.GetCheckoutHistory ( id ),
                Holds=_patron.GetHolds ( id )
            };

            return View ( model );
        }
    }
}

LibraryMngmnt.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryManagement.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link href="https://fonts.googleapis.com/css?family=Coda" rel="stylesheet">
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
        <link href=”//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css” rel=”stylesheet”>
        <link href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">@ViewData["Title"]</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-nav">
                <a class="nav-item nav-link" asp-controller="Home" asp-action="Index">Home</a>
                <a class="nav-tem nav-link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                <a class="nav-item nav-link" asp-controller="Patron" asp-action="Index">Patrons</a>
                <a class="nav-item nav-link" asp-controller="Branch" asp-action="Index">Branches</a>

            </div>

        </nav>

        <div class="page-content">
            @RenderBody( )
        </div>
    </div>

    @RenderSection( "Scripts", required: false )
    @RenderSection( "Styles", required: false )
    <script src="https://use.fontawesome.com/6110b02b27.js"></script>

</body>
</html>